<meta charset="UTF-8">
<meta name="author" content="UC Berkeley GamesCrafters Research Group">
<meta name="description" content="A research and development group formed by Dr. Dan Garcia in 2001 to explore the fertile area of combinatorial and computational game theory.">
<meta name="copyright" content="&copy; GamesCrafters">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= $pageTitle ?></title>
<link rel="shortcut icon" href="/site-legacy-archive-sp20/resources/gc.png" type="image/png">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Public+Sans:400,400i,600,600i&display=swap">
<link rel="stylesheet" href="/site-refresh-sp20/assets/main.css">
<script type="text/javascript">

    window.addEventListener("DOMContentLoaded", function () {

        document.querySelectorAll("[data-src-on-hover]").forEach(function (node) {
            const src = node.src;
            node.addEventListener("mouseover", function () {
                this.src = this.dataset.srcOnHover;
            });
            node.addEventListener("mouseout", function () {
                this.src = src;
            });
        });

        document.querySelectorAll(".page-content h3[id]").forEach(function (node) {
            node.addEventListener("click", function () {
                // Update location hash
                window.location.hash = this.id;
            });
        });

    });

</script>
<script type="text/javascript">
    const gaJsHost = ("https:" === document.location.protocol) ? "https://ssl." : "http://www.";
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
    const pageTracker = _gat._getTracker("UA-3581208-1");
    pageTracker._initData();
    pageTracker._trackPageview();
</script>
