<div class="page-logo">
    <a id="imagemap-home" class="imagemap" href="./" title="GamesCrafters Home">GamesCrafters</a>
    <a id="imagemap-g" class="imagemap letter" href="games.php" title="Games">Games</a>
    <a id="imagemap-a" class="imagemap letter" href="analysis.php" title="Analysis">Analysis</a>
    <a id="imagemap-m" class="imagemap letter" href="members.php" title="Members">Members</a>
    <a id="imagemap-e" class="imagemap letter" href="extra.php" title="Extra">Extra</a>
    <a id="imagemap-s" class="imagemap letter" href="software.php" title="Software">Software</a>
</div>
<div class="page-nav">
    <h1><a href="./">GamesCrafters</a></h1>
    <nav>
        <ul>
            <li><a href="games.php" title="Games">Games</a></li>
            <li><a href="analysis.php" title="Analysis">Analysis</a></li>
            <li><a href="members.php" title="Members">Members</a></li>
            <li><a href="extra.php" title="Extra">Extra</a></li>
            <li><a href="software.php" title="Software">Software</a></li>
        </ul>
    </nav>
</div>
